# Generated by Django 2.2.4 on 2019-09-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status_pagamento',
            field=models.IntegerField(blank=True, choices=[(0, 'Não Pago'), (1, 'Processando pedido'), (2, 'Pago')], default=0),
        ),
    ]
