# Generated by Django 2.2.4 on 2019-09-14 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190914_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenspedido',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='api.Produto'),
        ),
    ]
